export default [
  {
    _id: "C01",
    name: "Defense Against the Dark Arts",
    number: "HP0001",
    startDate: "2023-09-01",
    endDate: "2024-06-15",
    department: "Gryffindor",
    credit: "4",
    description: "This course will teach you how to defend yourself against the dark arts.",
    image: "C01.jpg",
  },
  {
    _id: "C02",
    name: "Potions",
    number: "HP0002",
    startDate: "2023-09-01",
    endDate: "2024-06-15",
    department: "Gryffindor",
    credit: "4",
    description: "This course will teach you how to brew potions.",
    image: "C02.jpg",
  },
  {
    _id: "C03",
    name: "Transfiguration",
    number: "HP0003",
    startDate: "2023-09-01",
    endDate: "2024-06-15",
    department: "Gryffindor",
    credit: "4",
    description: "This course will teach you how to transfigure objects.",
    image: "C03.jpg",
  },
  {
    _id: "C04",
    name: "Charms",
    number: "HP0004",
    startDate: "2023-09-01",
    endDate: "2024-06-15",
    department: "Gryffindor",
    credit: "4",
    description: "This course will teach you how to cast charms.",
    image: "C04.jpg",
  },
  {
    _id: "C05",
    name: "Herbology",
    number: "HP0005",
    startDate: "2023-09-01",
    endDate: "2024-06-15",
    department: "Gryffindor",
    credit: "4",
    description: "This course will teach you about magical plants.",
    image: "C05.jpg",
  },
  {
    _id: "C06",
    name: "Astronomy",
    number: "HP0006",
    startDate: "2023-09-01",
    endDate: "2024-06-15",
    department: "Gryffindor",
    credit: "4",
    description: "This course will teach you about the stars and planets.",
    image: "C06.jpg",
  },
  {
    _id: "C07",
    name: "History of Magic",
    number: "HP0007",
    startDate: "2023-09-01",
    endDate: "2024-06-15",
    department: "Gryffindor",
    credit: "4",
    description: "This course will teach you about the history of magic.",
    image: "C07.jpg",
  },
  {
    _id: "C08",
    name: "Care of Magical Creatures",
    number: "HP0008",
    startDate: "2023-09-01",
    endDate: "2024-06-15",
    department: "Gryffindor",
    credit: "4",
    description: "This course will teach you how to care for magical creatures.",
    image: "C08.jpg",
  },
]
